
auth.token=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

defaults.org=chefu-technologies
defaults.project=infinity

defaults.url=https://sentry.io/
